In [5]:
import pandas as pd

In [ ]:
data={
    "employee":["riya","salu","raju","manu","winu","ammu"],
    "department":["it","hr","it","finance","hr","it"],
    "city":["bangalore","chennai","bangalore","delhi","chennai","mumbai"],
    "salary":[6000,5000,65000,7000,52000,58000],
    "experience":[5,3,7,10,4,6]
}
df = pd.DataFrame(data)
df

  employee department       city  salary  experience
0     riya         it  bangalore    6000           5
1     salu         hr    chennai    5000           3
2     raju         it  bangalore   65000           7
3     manu    finance      delhi    7000          10
4     winu         hr    chennai   52000           4
5     ammu         it     mumbai   58000           6

In [19]:
df.groupby("department")

In [20]:
df.groupby("department")["salary"].mean()

department
finance     7000.0
hr         28500.0
it         43000.0
Name: salary, dtype: float64

In [21]:
df.groupby("department")["salary"].sum()

department
finance      7000
hr          57000
it         129000
Name: salary, dtype: int64

In [22]:
df.groupby("department")["salary"].max()

department
finance     7000
hr         52000
it         65000
Name: salary, dtype: int64

In [23]:
df.groupby("department")["salary"].agg(["mean","sum","min","max"])

               mean     sum   min    max
department
finance      7000.0    7000  7000   7000
hr          28500.0   57000  5000  52000
it          43000.0  129000  6000  65000

In [24]:
df.groupby("department").agg(
    avg_salary=("salary", "mean"),
    total_salary=("salary","sum"),
    max_experience=("experience","max")
)

            avg_salary  total_salary  max_experience
department
finance         7000.0          7000              10
hr             28500.0         57000               4
it             43000.0        129000               7

In [48]:
employees=pd.DataFrame({
    "empid":[1,2,3,4],
    "name":["chinnu", "salu","saabi","bavu"],
    "Dept id":[101,102,101,103],
    "salary":[60000,50000,65000,70000]
})
departments=pd.DataFrame({
    "Dept id":[101,102,104],
    "Department":["it","hr","finance"]
})
employees,departments

(   empid    name  Dept id  salary
 0      1  chinnu      101   60000
 1      2    salu      102   50000
 2      3   saabi      101   65000
 3      4    bavu      103   70000,
    Dept id Department
 0      101         it
 1      102         hr
 2      104    finance)

In [50]:
pd.merge(employees, departments, on="Dept id",how="inner")

   empid    name  Dept id  salary Department
0      1  chinnu      101   60000         it
1      2    salu      102   50000         hr
2      3   saabi      101   65000         it

In [51]:
pd.merge(employees, departments, on="Dept id",how="left")

   empid    name  Dept id  salary Department
0      1  chinnu      101   60000         it
1      2    salu      102   50000         hr
2      3   saabi      101   65000         it
3      4    bavu      103   70000        NaN

In [52]:
pd.merge(employees, departments, on="Dept id",how="right")

   empid    name  Dept id   salary Department
0    1.0  chinnu      101  60000.0         it
1    3.0   saabi      101  65000.0         it
2    2.0    salu      102  50000.0         hr
3    NaN     NaN      104      NaN    finance

In [53]:
pd.merge(employees, departments, on="Dept id",how="outer")

   empid    name  Dept id   salary Department
0    1.0  chinnu      101  60000.0         it
1    3.0   saabi      101  65000.0         it
2    2.0    salu      102  50000.0         hr
3    4.0    bavu      103  70000.0        NaN
4    NaN     NaN      104      NaN    finance

In [54]:
pd.merge(employees, departments, on="Dept id")

   empid    name  Dept id  salary Department
0      1  chinnu      101   60000         it
1      2    salu      102   50000         hr
2      3   saabi      101   65000         it

In [55]:
employees.set_index("Dept id",inplace=True)

In [57]:
departments.set_index("Dept id",inplace=True)
employees.join(departments)

         empid    name  salary Department
Dept id
101          1  chinnu   60000         it
102          2    salu   50000         hr
101          3   saabi   65000         it
103          4    bavu   70000        NaN

In [58]:
df1=employees.iloc[:2]
df2=employees.iloc[2:]
pd.concat([df1,df2])

         empid    name  salary
Dept id
101          1  chinnu   60000
102          2    salu   50000
101          3   saabi   65000
103          4    bavu   70000

In [59]:
extra=pd.DataFrame({"bonus":[5000,6000,5500,7000]})
pd.concat([employees.reset_index(drop=True),extra],axis=1)

   empid    name  salary  bonus
0      1  chinnu   60000   5000
1      2    salu   50000   6000
2      3   saabi   65000   5500
3      4    bavu   70000   7000

In [61]:
pd.concat([df1,df2])

         empid    name  salary
Dept id
101          1  chinnu   60000
102          2    salu   50000
101          3   saabi   65000
103          4    bavu   70000