In [1]:
import pandas as pd

In [3]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from openpyxl) (2.0.0)

In [3]:
import pandas as pd

In [93]:
df=pd.read_excel(r"C:\Users\USER\Downloads\dataset\cardata.xlsx")

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [74]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [94]:
df=pd.read_excel(r"C:\Users\USER\Downloads\dataset\cardata.xlsx")

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [2]:
!C:\Users\USER\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.3824.0_x64__qbz5n2kfra8p0\Lib\site-packages (26.1.2)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (262 kB/1.8 MB, attempt 1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/f3/6e/1736e5b4ae2b778ef2f81c47d797de9f891d4d8acb047a24ca37a60294dd/pip-26.2.1-py3-none-any.whl
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (262 kB/1.8 MB, attempt 2)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (262 kB/1.8 MB, attempt 3)
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (1.6 MB/1.8 MB, attempt 4)

In [60]:
df

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [61]:
df.head(15)

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
5,Maruti Alto LX BSIII,2007,125000,Petrol,Individual,Manual,First Owner,19
6,Hyundai Xcent 1.2 Kappa S,2016,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,60000,Petrol,Individual,Manual,Second Owner,12
8,Hyundai Creta 1.6 VTVT S,2015,25000,Petrol,Individual,Manual,First Owner,11
9,Maruti Celerio Green VXI,2017,78000,CNG,Individual,Manual,First Owner,9
10,Chevrolet Sail 1.2 Base,2015,35000,Petrol,Individual,Manual,First Owner,11
11,Tata Indigo Grand Petrol,2014,100000,Petrol,Individual,Manual,First Owner,12
12,Toyota Corolla Altis 1.8 VL CVT,2018,25000,Petrol,Dealer,Automatic,First Owner,8
13,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
14,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19

In [62]:
df.tail(10)

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
4330,Tata Indica Vista Aqua 1.4 TDI,2010,130000,Diesel,Individual,Manual,Second Owner,16
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,175000,Diesel,Individual,Manual,Third Owner,11
4332,Mahindra Scorpio S2 7 Seater,2015,120000,Diesel,Individual,Manual,First Owner,11
4333,Maruti Ritz VDi,2012,90000,Diesel,Individual,Manual,Second Owner,14
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [63]:
df.to_string()

'                                                            name  year  km_driven      fuel       seller_type transmission                 owner  Age\n0                                                  Maruti 800 AC  2007      70000    Petrol        Individual       Manual           First Owner   19\n1                                       Maruti Wagon R LXI Minor  2007      50000    Petrol        Individual       Manual           First Owner   19\n2                                           Hyundai Verna 1.6 SX  2012     100000    Diesel        Individual       Manual           First Owner   14\n3                                         Datsun RediGO T Option  2017      46000    Petrol        Individual       Manual           First Owner    9\n4                                          Honda Amaze VX i-DTEC  2014     141000    Diesel        Individual       Manual          Second Owner   12\n5                                           Maruti Alto LX BSIII  2007     125000    Petrol        Individual       Manual           First Owner   19\n6                                      Hyundai Xcent 1.2 Kappa S  2016      25000    Petrol        Individual       Manual           First Owner   10\n7                                       Tata Indigo Grand Petrol  2014      60000    Petrol        Individual       Manual          Second Owner   12\n8                                       Hyundai Creta 1.6 VTVT S  2015      25000    Petrol        Individual       Manual           First Owner   11\n9                                       Maruti Celerio Green VXI  2017      78000       CNG        Individual       Manual           First Owner    9\n10                                       Chevrolet Sail 1.2 Base  2015      35000    Petrol        Individual       Manual           First Owner   11\n11                                      Tata Indigo Grand Petrol  2014     100000    Petrol        Individual       Manual           First Owner   12\n12                               Toyota Corolla Altis 1.8 VL CVT  2018      25000    Petrol            Dealer    Automatic           First Owner    8\n13                                                 Maruti 800 AC  2007      70000    Petrol        Individual       Manual           First Owner   19\n14                                      Maruti Wagon R LXI Minor  2007      50000    Petrol        Individual       Manual           First Owner   19\n15                                          Hyundai Verna 1.6 SX  2012     100000    Diesel        Individual       Manual           First Owner   14\n16                                        Datsun RediGO T Option  2017      46000    Petrol        Individual       Manual           First Owner    9\n17                                         Honda Amaze VX i-DTEC  2014     141000    Diesel        Individual       Manual          Second Owner   12\n18                                          Maruti Alto LX BSIII  2007     125000    Petrol        Individual       Manual           First Owner   19\n19                                     Hyundai Xcent 1.2 Kappa S  2016      25000    Petrol        Individual       Manual           First Owner   10\n20                                      Tata Indigo Grand Petrol  2014      60000    Petrol        Individual       Manual          Second Owner   12\n21                                      Hyundai Creta 1.6 VTVT S  2015      25000    Petrol        Individual       Manual           First Owner   11\n22                                      Maruti Celerio Green VXI  2017      78000       CNG        Individual       Manual           First Owner    9\n23                                       Chevrolet Sail 1.2 Base  2015      35000    Petrol        Individual       Manual           First Owner   11\n24                                      Tata Indigo Grand Petrol  2014     100000    Petrol        Individual       Manual           First Owner   12\n25                               Toyota Corolla Altis 1.8 VL CVT  2018      25000    Petrol            Dealer    Automatic           First Owner    8\n26                                          Maruti Ciaz VXi Plus  2015      24000    Petrol            Dealer       Manual           First Owner   11\n27                                   Hyundai Venue SX Opt Diesel  2019       5000    Diesel            Dealer       Manual           First Owner    7\n28                             Chevrolet Enjoy TCDi LTZ 7 Seater  2013      33000    Diesel        Individual       Manual          Second Owner   13\n29                                    Jaguar XF 2.2 Litre Luxury  2014      28000    Diesel            Dealer    Automatic           First Owner   12\n30                          Mercedes-Benz New C-Class 220 CDI AT  2013      59000    Diesel            Dealer    Automatic           First Owner   13\n31                             Maruti Vitara Brezza ZDi Plus AMT  2018       4500    Diesel            Dealer    Automatic           First Owner    8\n32                                               Audi Q5 2.0 TDI  2011     175900    Diesel            Dealer    Automatic           First Owner   15\n33                                               Honda City V MT  2018      14500    Petrol            Dealer       Manual           First Owner    8\n34                                    Tata Tigor 1.2 Revotron XT  2018      15000    Petrol        Individual       Manual           First Owner    8\n35                               Audi A6 2.0 TDI  Design Edition  2013      50000    Diesel            Dealer    Automatic           First Owner   13\n36                Mercedes-Benz New C-Class C 220 CDI Avantgarde  2012      33800    Diesel            Dealer    Automatic          Second Owner   14\n37                           Skoda Superb Ambition 2.0 TDI CR AT  2011     130400    Diesel            Dealer    Automatic          Second Owner   15\n38                                     Toyota Corolla Altis G AT  2016      50000    Petrol        Individual    Automatic           First Owner   10\n39                         Toyota Innova 2.5 G (Diesel) 7 Seater  2015      80000    Diesel        Individual       Manual           First Owner   11\n40                              Jeep Compass 1.4 Sport Plus BSIV  2019      10000    Petrol        Individual       Manual           First Owner    7\n41                      Mercedes-Benz E-Class E 200 CGI Elegance  2010     119000    Petrol            Dealer    Automatic           First Owner   16\n42                                        Hyundai i10 Magna 1.1L  2014      60000    Petrol        Individual       Manual  Fourth & Above Owner   12\n43                                  BMW 3 Series 320d Sport Line  2013      75800    Diesel            Dealer    Automatic          Second Owner   13\n44                                Audi Q7 35 TDI Quattro Premium  2009      78000    Diesel            Dealer    Automatic           Third Owner   17\n45                                        Hyundai Elantra CRDi S  2012      40000    Diesel        Individual       Manual           First Owner   14\n46                                     Mahindra Scorpio 1.99 S10  2014      50000    Diesel        Individual       Manual           First Owner   12\n47                                           Honda City i DTEC V  2014      74000    Diesel        Individual       Manual          Second Owner   12\n48                             Maruti Wagon R VXI BS IV with ABS  2014      64000    Petrol        Individual       Manual          Second Owner   12\n49                                      Maruti Wagon R VXI BS IV  2012      60000    Petrol        Individual       Manual          Second Owner   14\n50                                           Mahindra Scorpio LX  2009     120000    Diesel        Individual       Manual          Second Owner   17\n51                                       Hyundai Santro Xing GLS  2009      79000    Petrol        Individual       Manual           Third Owner   17\n52                              Hyundai Grand i10 1.2 Kappa Asta  2019      15000    Petrol        Individual       Manual           First Owner    7\n53                                               Maruti Alto LXi  2006      80000    Petrol        Individual       Manual           First Owner   20\n54                               Maruti Swift Dzire VDI Optional  2017      18500    Diesel            Dealer       Manual           First Owner    9\n55                                  Maruti Eeco 5 Seater AC BSIV  2018      10200    Petrol            Dealer       Manual           First Owner    8\n56                                   Hyundai i20 Sportz 1.4 CRDi  2018      29000    Diesel            Dealer       Manual           First Owner    8\n57    Maruti Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER  2018      28000    Petrol            Dealer       Manual           First Owner    8\n58                                         Maruti Swift ZDi BSIV  2016      46000    Diesel            Dealer       Manual           First Owner   10\n59                  Hyundai i20 2015-2017 Sportz Option 1.4 CRDi  2014      70000    Diesel            Dealer       Manual           First Owner   12\n60                                               Maruti Alto LXi  2012      60000    Petrol        Individual       Manual          Second Owner   14\n61                                      Mahindra Jeep CL 500 MDI  1996      35000    Diesel        Individual       Manual          Second Owner   30\n62                                          Honda City i DTEC VX  2014      90000    Diesel            Dealer       Manual           First Owner   12\n63                                      Maruti Wagon R VXI BS IV  2013      80000    Petrol            Dealer       Manual           First Owner   13\n64                                               Tata Indica DLS  2005      80000    Diesel        Individual       Manual           First Owner   21\n65                                        Hyundai EON Magna Plus  2014      73300    Petrol            Dealer       Manual          Second Owner   12\n66                                               Toyota Etios GD  2014      92000    Diesel            Dealer       Manual           First Owner   12\n67                                               Maruti Alto LXi  2009      66764    Petrol            Dealer       Manual          Second Owner   17\n68                                               Maruti Alto LXi  2009     100000    Petrol        Individual       Manual           First Owner   17\n69                 Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII  2010     350000    Diesel        Individual       Manual          Second Owner   16\n70                              Toyota Corolla Altis Diesel D4DG  2011     230000    Diesel        Individual       Manual           First Owner   15\n71                                 Mahindra Scorpio 1.99 S6 Plus  2017      60000    Diesel        Individual       Manual           First Owner    9\n72                                        Hyundai EON Magna Plus  2018      31000    Petrol        Individual       Manual           First Owner    8\n73                                     Tata Indigo Classic Dicor  2007      39000    Diesel        Individual       Manual           First Owner   19\n74                           Toyota Innova 2.5 V Diesel 8-seater  2009     120000    Diesel        Individual       Manual           Third Owner   17\n75                                Tata Indica Vista Quadrajet LS  2014     166000    Diesel        Individual       Manual  Fourth & Above Owner   12\n76                                          Maruti Swift 1.3 VXi  2006     110000    Petrol        Individual       Manual           Third Owner   20\n77                        Ford EcoSport 1.5 Diesel Titanium BSIV  2017      35000    Diesel        Individual       Manual           First Owner    9\n78                                         Maruti Ciaz 1.3 Delta  2018      60000    Diesel        Individual       Manual           First Owner    8\n79                                          Honda Civic 1.8 V AT  2007      54000    Petrol        Individual    Automatic          Second Owner   19\n80                                        Hyundai i10 Sportz 1.2  2010      63000    Petrol        Individual       Manual          Second Owner   16\n81                                  Skoda Rapid 1.5 TDI Elegance  2014     120000    Diesel        Individual       Manual          Second Owner   12\n82                                              Hyundai Getz GLS  2005     120000    Petrol        Individual       Manual           Third Owner   21\n83                                             Nissan Terrano XL  2014      76000    Petrol        Individual       Manual          Second Owner   12\n84                                 Hyundai Grand i10 CRDi Sportz  2015      80000    Diesel        Individual       Manual           First Owner   11\n85                                  Hyundai Elite i20 Diesel Era  2019      25000    Diesel        Individual       Manual           First Owner    7\n86                                          Honda Amaze S i-VTEC  2016      11958    Petrol            Dealer       Manual           First Owner   10\n87                                               Honda Brio S MT  2015      20000    Petrol            Dealer       Manual           First Owner   11\n88                                   Hyundai Creta 1.6 SX Option  2017       9000    Petrol            Dealer       Manual           First Owner    9\n89             Mercedes-Benz S-Class S 350d Connoisseurs Edition  2017       6500    Diesel            Dealer    Automatic           First Owner    9\n90                                        Mahindra XUV500 W8 2WD  2015      70000    Diesel        Individual       Manual           First Owner   11\n91                       Renault Duster 85PS Diesel RxL Optional  2013     120000    Diesel        Individual       Manual           First Owner   13\n92                                        Hyundai Santro Xing XO  2007      58000    Petrol            Dealer       Manual          Second Owner   19\n93                                 Mahindra Bolero 2011-2019 SLE  2013      62200    Diesel            Dealer       Manual           First Owner   13\n94                                  Audi A6 2.0 TDI Premium Plus  2014      34000    Diesel            Dealer    Automatic          Second Owner   12\n95                               Fiat Avventura MULTIJET Emotion  2015      53000    Diesel        Individual       Manual          Second Owner   11\n96                                               Audi A8 4.2 TDI  2013      49000    Diesel            Dealer    Automatic           First Owner   13\n97                                           Datsun RediGO 1.0 S  2017      15000    Petrol            Dealer       Manual          Second Owner    9\n98                          Volkswagen Jetta 1.4 TSI Comfortline  2013      50000    Petrol        Individual       Manual           First Owner   13\n99                          Audi A4 2.0 TDI 177 Bhp Premium Plus  2013      53000    Diesel            Dealer    Automatic           First Owner   13\n100                                         Honda Civic 1.8 V AT  2009      63500    Petrol            Dealer    Automatic           First Owner   17\n101                   Mercedes-Benz E-Class Exclusive E 200 BSIV  2018       9800    Petrol            Dealer    Automatic           First Owner    8\n102                                      BMW X1 sDrive 20d xLine  2017      13000    Diesel        Individual    Automatic           First Owner    9\n103                                        Volvo V40 D3 R Design  2018      21000    Diesel            Dealer    Automatic           First Owner    8\n104                                         Maruti SX4 Zxi BSIII  2008      29173    Petrol            Dealer       Manual           First Owner   18\n105                                           BMW 7 Series 730Ld  2012      48000    Diesel            Dealer    Automatic           First Owner   14\n106                               Mahindra Bolero Power Plus SLX  2017     120000    Diesel        Individual       Manual           First Owner    9\n107                                      Hyundai Sonata CRDi M/T  2010     100000    Diesel        Individual       Manual           First Owner   16\n108                                Nissan Micra Active XV Petrol  2017      30000    Petrol        Individual       Manual           First Owner    9\n109                                             Mahindra Xylo D4  2018      87000    Diesel        Individual       Manual           First Owner    8\n110                 Hyundai Elite i20 Sportz Plus Dual Tone BSIV  2019      15000    Petrol        Individual       Manual           First Owner    7\n111                                             Renault KWID RXT  2017      16000    Petrol        Individual       Manual           First Owner    9\n112                                      Mahindra Xylo E4 BS III  2012      60000    Diesel        Individual       Manual           First Owner   14\n113                                     Maruti Wagon R LXI Minor  2010      60000    Petrol        Individual       Manual  Fourth & Above Owner   16\n114                                       Maruti SX4 ZXI MT BSIV  2011     110000    Petrol        Individual       Manual           Third Owner   15\n115                                             Renault KWID RXT  2017      25000    Petrol        Individual       Manual           First Owner    9\n116                                     Hyundai Creta 1.4 CRDi S  2016      60000    Diesel        Individual       Manual           First Owner   10\n117                                       Maruti Swift Dzire VDI  2014      79350    Diesel        Individual       Manual          Second Owner   12\n118                           Hyundai Verna 1.6 VTVT AT S Option  2016      80000    Petrol        Individual    Automatic           First Owner   10\n119                                     Mahindra Scorpio LX BSIV  2014      90000    Diesel        Individual       Manual          Second Owner   12\n120                                         Maruti SX4 Vxi BSIII  2007      90000    Petrol        Individual       Manual          Second Owner   19\n121                                            Maruti Ertiga VDI  2014     120000    Diesel        Individual       Manual          Second Owner   12\n122                                        Chevrolet Beat Diesel  2013      60000    Diesel        Individual       Manual          Second Owner   13\n123                                                Maruti Zen LX  2004      50000    Petrol        Individual       Manual           First Owner   22\n124                                      Maruti Baleno Delta 1.2  2018      20000    Petrol        Individual       Manual           First Owner    8\n125                                       Maruti Swift Vdi BSIII  2007     110000    Diesel        Individual       Manual  Fourth & Above Owner   19\n126                                            Tata Nano Lx BSIV  2012      50000    Petrol        Individual       Manual          Second Owner   14\n127                       Toyota Innova 2.5 GX (Diesel) 8 Seater  2012     100000    Diesel        Individual       Manual           First Owner   14\n128                                       Maruti Ertiga SHVS VDI  2016      70000    Diesel        Individual       Manual          Second Owner   10\n129                                    Hyundai Creta 1.6 CRDi SX  2016      70000    Diesel        Individual       Manual          Second Owner   10\n130                                        Honda Amaze S i-Vtech  2016      50000    Petrol        Individual       Manual           First Owner   10\n131                               Tata Indica Vista Aqua 1.4 TDI  2

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          4340 non-null   str
 1   year          4340 non-null   int64
 2   km_driven     4340 non-null   int64
 3   fuel          4340 non-null   str
 4   seller_type   4340 non-null   str
 5   transmission  4340 non-null   str
 6   owner         4340 non-null   str
 7   Age           4340 non-null   int64
dtypes: int64(3), str(5)
memory usage: 271.4 KB

In [65]:
df.describe()

              year      km_driven          Age
count  4340.000000    4340.000000  4340.000000
mean   2013.090783   66215.777419    12.909217
std       4.215344   46644.102194     4.215344
min    1992.000000       1.000000     6.000000
25%    2011.000000   35000.000000    10.000000
50%    2014.000000   60000.000000    12.000000
75%    2016.000000   90000.000000    15.000000
max    2020.000000  806599.000000    34.000000

In [72]:
df

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [53]:
df

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [21]:
df=df.drop("new_selling_price",axis=1)

In [22]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [33]:
df

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [35]:
df2=df[df["year"]>2010]

In [36]:
df2

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
6,Hyundai Xcent 1.2 Kappa S,2016,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,60000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [40]:
df2=df2.sort_values("selling_price")

KeyError: 'selling_price'

In [41]:
df2

,name,year,km_driven,fuel,seller_type,transmission,owner,Age
2,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,12
6,Hyundai Xcent 1.2 Kappa S,2016,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,60000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,80000,Diesel,Individual,Manual,Second Owner,12
4338,Hyundai Creta 1.6 CRDi SX Option,2016,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,40000,Petrol,Individual,Manual,First Owner,10

In [43]:
import pandas as pd

In [50]:
df5=pd.read_excel(r"C:\Users\USER\Downloads\dataset\cardata.xlsx",header=None)

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [75]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [95]:
df["new_selling_price"]=df["selling_price"]+df["km_driven"]

In [96]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age,new_selling_price
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19,130000
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19,185000
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14,700000
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9,296000
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12,591000
...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12,489999
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12,489999
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17,193000
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10,955000
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10,265000

In [97]:
df=df.drop("new_selling_price",axis=1)

In [98]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [100]:
df2=df[df["year"]>2010]

In [101]:
df2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner,10
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner,14
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [102]:
df3=df[df["fuel"]=="petrol"]

In [103]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [104]:
df2.sort_values("selling_price",inplace=True)

In [105]:
df2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,14
877,Tata Nano Std,2011,40000,19000,Petrol,Individual,Manual,First Owner,15
1468,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
3087,Tata Nano Lx BSIV,2012,45000,35000,Petrol,Individual,Manual,Second Owner,14
4158,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,10
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,9
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,10

In [107]:
df2.to_excel("C:/Users/USER/Downloads/dataset/cardata.xlsx")

In [108]:
df2

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,14
877,Tata Nano Std,2011,40000,19000,Petrol,Individual,Manual,First Owner,15
1468,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
3087,Tata Nano Lx BSIV,2012,45000,35000,Petrol,Individual,Manual,Second Owner,14
4158,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,10
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,9
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,10

In [109]:
import pandas as pd

In [112]:
df5=pd.read_excel("C:/Users/USER/Downloads/dataset/cardata.xlsx",header=None)

In [116]:
df5

,,,id,name,age,gender,salery,dep,date
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,14
877,Tata Nano Std,2011,40000,19000,Petrol,Individual,Manual,First Owner,15
1468,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
3087,Tata Nano Lx BSIV,2012,45000,35000,Petrol,Individual,Manual,Second Owner,14
4158,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,10
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,9
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,10

In [117]:
df5=pd.read_excel("C:/Users/USER/Downloads/dataset/cardata.xlsx",names=["id","name","age","gender","salery","dep","date"])

In [118]:
df5

,,,id,name,age,gender,salery,dep,date
1832,Tata Nano LX SE,2012,35000,35000,Petrol,Individual,Manual,Third Owner,14
877,Tata Nano Std,2011,40000,19000,Petrol,Individual,Manual,First Owner,15
1468,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
3087,Tata Nano Lx BSIV,2012,45000,35000,Petrol,Individual,Manual,Second Owner,14
4158,Tata Nano Cx BSIII,2014,45000,7000,Petrol,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
2239,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
2258,BMW X5 xDrive 30d xLine,2019,4950000,30000,Diesel,Dealer,Automatic,First Owner,7
3969,Mercedes-Benz GLS 2016-2020 350d 4MATIC,2016,5500000,77350,Diesel,Dealer,Automatic,First Owner,10
89,Mercedes-Benz S-Class S 350d Connoisseurs Edition,2017,8150000,6500,Diesel,Dealer,Automatic,First Owner,9
3872,Audi RS7 2015-2019 Sportback Performance,2016,8900000,13000,Petrol,Dealer,Automatic,First Owner,10

In [121]:
df.loc[0:3]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9