In [3]:
import pandas as pd

In [4]:
data={
    "customer":["priya","AMIT","rahul","amit"],
    "email":["priya@gmail.com","laya@gmailo.com","rahul@gmail.com","sneha@gmail.com"],
    "phone":["+91-9876643210","9876643211","9876643212","98766432123"],
    "amount":["$1200","1500 INR","Rs.2000","1500"]
}
df=pd.DataFrame(data)
df

  customer            email           phone    amount
0    priya  priya@gmail.com  +91-9876643210     $1200
1     AMIT  laya@gmailo.com      9876643211  1500 INR
2    rahul  rahul@gmail.com      9876643212   Rs.2000
3     amit  sneha@gmail.com     98766432123      1500

In [5]:
df["customer"]=df["customer"].str.strip()
df

  customer            email           phone    amount
0    priya  priya@gmail.com  +91-9876643210     $1200
1     AMIT  laya@gmailo.com      9876643211  1500 INR
2    rahul  rahul@gmail.com      9876643212   Rs.2000
3     amit  sneha@gmail.com     98766432123      1500

In [6]:
df["customer"]=df["customer"].str.lower()
df

  customer            email           phone    amount
0    priya  priya@gmail.com  +91-9876643210     $1200
1     amit  laya@gmailo.com      9876643211  1500 INR
2    rahul  rahul@gmail.com      9876643212   Rs.2000
3     amit  sneha@gmail.com     98766432123      1500

In [7]:
df["amount"]=df["amount"].str.replace("Rs." ,"")
df

  customer            email           phone    amount
0    priya  priya@gmail.com  +91-9876643210     $1200
1     amit  laya@gmailo.com      9876643211  1500 INR
2    rahul  rahul@gmail.com      9876643212      2000
3     amit  sneha@gmail.com     98766432123      1500

In [8]:
df["amount"]=df["amount"].str.replace(r"[INR.-]","",regex=True)
df

  customer            email           phone amount
0    priya  priya@gmail.com  +91-9876643210  $1200
1     amit  laya@gmailo.com      9876643211  1500
2    rahul  rahul@gmail.com      9876643212   2000
3     amit  sneha@gmail.com     98766432123   1500

In [9]:
df["amount"]=df["amount"].str.replace("$" ,"")
df

  customer            email           phone amount
0    priya  priya@gmail.com  +91-9876643210   1200
1     amit  laya@gmailo.com      9876643211  1500
2    rahul  rahul@gmail.com      9876643212   2000
3     amit  sneha@gmail.com     98766432123   1500

In [10]:
df["phone"]=df["phone"].str.replace(r"[-+91]","",regex=True)
df

  customer            email      phone amount
0    priya  priya@gmail.com   87664320   1200
1     amit  laya@gmailo.com    8766432  1500
2    rahul  rahul@gmail.com   87664322   2000
3     amit  sneha@gmail.com  876643223   1500

In [11]:
df["phone"]="+91"+df["phone"].astype(str)
df

  customer            email         phone amount
0    priya  priya@gmail.com   +9187664320   1200
1     amit  laya@gmailo.com    +918766432  1500
2    rahul  rahul@gmail.com   +9187664322   2000
3     amit  sneha@gmail.com  +91876643223   1500

In [12]:
data={
    "customer":["priya","AMIT","rahul","amit"],
    "email":["priya@gmail.com","priya@gmailo.com","rahul@gmail.com","sneha@gmail.com"],
    "phone":["+91-9876643210","9876643211","9876643212","98766432123"],
    "amount":["1200","1500 INR","Rs.2000","1500"]
}
df=pd.DataFrame(data)
df

  customer             email           phone    amount
0    priya   priya@gmail.com  +91-9876643210      1200
1     AMIT  priya@gmailo.com      9876643211  1500 INR
2    rahul   rahul@gmail.com      9876643212   Rs.2000
3     amit   sneha@gmail.com     98766432123      1500

In [13]:
df["amount"]=df["amount"].str.replace(r"[^\d\s]","",regex=True)
df

  customer             email           phone amount
0    priya   priya@gmail.com  +91-9876643210   1200
1     AMIT  priya@gmailo.com      9876643211  1500
2    rahul   rahul@gmail.com      9876643212   2000
3     amit   sneha@gmail.com     98766432123   1500